import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/shared/Nav";
import toast, { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">

      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav></Nav>
        <main className="max-w-7xl px-4  md:px-6 lg:px-8 mx-auto">
          {children}
          <Toaster></Toaster>
        </main>
      </body>
    </html>
  );
}
